name: CI/CD Project Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'data/**'
      - 'compose.yaml'
      - '.github/workflows/ci.yml'

  pull_request:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'data/**'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Workspace
        run: |
          # Запускаємо мультиконтейнерний стек у фоновому режимі
          docker compose up --build -d
          
          # Даємо час батч-контейнерам послідовно виконати всі розрахунки
          sleep 25

      - name: Display Container Statuses
        run: |
          # Виводимо список усіх контейнерів та їхніх статусів у лог для викладача
          docker compose ps -a

      - name: Shutdown Workspace and Clean Volumes
        if: always()
        run: |
          # Зупиняємо інфраструктуру конвеєра та очищуємо тимчасові томи
          docker compose down --volumes